export { default as CarouselComponent } from "./CarouselComponent/CarouselComponent";
export { default as Catalogue } from "./Catalogue/Catalogue";
export { default as InitialMenu } from "./InitialMenu/InitialMenu";
export { default as Footer } from "./Footer/Footer";
export { default as DatePicker } from "./DatePicker/DatePicker";
export { default as TimePicker } from "./TimePicker/TimePicker";
export { default as ThankyouPage } from "./ThankyouPage/ThankyouPage";
export { default as ServingPointsList } from "./ServingPointsList/ServingPointsList";
export { Review } from "./Review";
export { default as Header } from "./Header/Header";
export { default as CatalogueShortcuts } from "./CatalogueShortcuts/CatalogueShortcuts";
export { default as ScrollToTop } from "./ScrollToTop/ScrollToTop";
export { default as OpenBasket } from "./OpenBasket/OpenBasket";
export { default as SearchBar } from "./SearchBar/SearchBar";
export { default as CheckBox } from "./CheckBox/CheckBox";
export { default as OrderInfo } from "./OrderInfo/OrderInfo";
export { ConfirmationModal } from "./ConfirmationModal";
export { ConfirmationBackToHomeModal } from "./ConfirmationBackToHomeModal";
