const debugItem = {
  id: "820c1e75-2400-42aa-b8db-01ecb9f4df59",
  name: "Freddo Espresso",
  description: "",
  color: "#FFF",
  pictureUri: "",
  displayIndex: 0,
  printIndex: 0,
  allowZeroPrice: false,
  allowPriceInput: false,
  prices: [{ type: "All", value: 5.5 }],
  synthesis: {
    id: "d59875c2-3252-44bc-81cc-6fa3417f9143",
    name: "Freddo Espresso",
    synthesisModifiers: [
      {
        id: "581170c8-d3e0-4da4-b035-973f1e454b9e",
        name: "Μεγεθος",
        parentName: "Μεγεθος",
        color: "#FFF",
        pictureUri: "",
        displayIndex: 0,
        printIndex: 0,
        selectionBehavior: "Single",
        mandatory: true,
        subGroups: [],
        modifiers: [
          {
            id: "53a3fbd4-e365-4cb2-80f2-d3b6052e31a1",
            color: "#FFF",
            displayIndex: 0,
            printIndex: 0,
            name: "Μικρό",
            pictureUri: "",
            servingSpots: "TakeOut,Delivery",
            price: 0,
            increacesPrice: true,
            reducesPrice: true,
            isDefault: true,
            hasQuantity: true,
            maxQuantity: 5,
          },
          {
            id: "f8a57dce-6ac9-45ca-854e-3f65f2b49e28",
            color: "#FFF",
            displayIndex: 0,
            printIndex: 0,
            name: "Μεγάλο",
            pictureUri: "",
            servingSpots: "TakeOut,Delivery",
            price: 0,
            increacesPrice: true,
            reducesPrice: true,
            isDefault: false,
          },
        ],
      },
      {
        id: "605d33e8-d2ae-44b8-96d6-589441db83cd",
        name: "Χαρμάνι",
        parentName: "Χαρμάνι",
        color: "#FFF",
        pictureUri: "",
        displayIndex: 2,
        printIndex: 0,
        selectionBehavior: "Single",
        mandatory: true,
        subGroups: [],
        modifiers: [
          {
            id: "446cc0f9-33ad-4a32-b76d-5d9088865d81",
            color: "#FFF",
            displayIndex: 1,
            printIndex: 0,
            name: "Brazzilian",
            pictureUri: "",
            servingSpots: "All",
            price: 0,
            increacesPrice: true,
            reducesPrice: true,
            isDefault: false,
          },
          {
            id: "501d0202-20d4-4a8e-808e-3a77ade5f0e4",
            color: "#FFF",
            displayIndex: 2,
            printIndex: 0,
            name: "Arabbica",
            pictureUri: "",
            servingSpots: "All",
            price: 2,
            increacesPrice: true,
            reducesPrice: true,
            isDefault: false,
          },
          {
            id: "9fa5245d-c35d-489d-96dc-56cc27aadb79",
            color: "#FFF",
            displayIndex: 0,
            printIndex: 0,
            name: "Classico",
            pictureUri: "",
            servingSpots: "All",
            price: 1,
            increacesPrice: true,
            reducesPrice: true,
            isDefault: false,
            hasQuantity: true,
            maxQuantity: 5,
          },
        ],
      },
      {
        id: "e0d63703-ebb8-4cfc-8ec4-1dd427d307f7",
        name: "Επιλογή Ζάχαρης",
        parentName: "Επιλογή Ζάχαρης",
        color: "#FFF",
        pictureUri: "",
        displayIndex: 0,
        printIndex: 0,
        selectionBehavior: "Multiple",
        mandatory: true,
        subGroups: [
          {
            id: "08b24520-c91b-4014-993a-499c931b06a3",
            name: "Λευκή (Multiple)",
            parentName: "Επιλογή Ζάχαρης",
            color: "#FFF",
            pictureUri: "",
            displayIndex: 0,
            printIndex: 0,
            selectionBehavior: "Multiple",
            mandatory: false,
            subGroups: [],
            modifiers: [
              {
                id: "2fb6629d-f16c-4351-a797-d55b16cc3c89",
                color: "#FFF",
                displayIndex: 2,
                printIndex: 0,
                name: "Μέτριο",
                pictureUri: "",
                servingSpots: "All",
                price: 10,
                increacesPrice: true,
                reducesPrice: true,
                isDefault: false,
              },
              {
                id: "36996c21-e510-4851-8ecf-7699161b7ffa",
                color: "#FFF",
                displayIndex: 0,
                printIndex: 0,
                name: "Γλυκό",
                pictureUri: "",
                servingSpots: "All",
                price: 0,
                increacesPrice: true,
                reducesPrice: true,
                isDefault: false,
              },
              {
                id: "6261c8dd-98bd-46aa-91fd-4ac4db310c4a",
                color: "#FFF",
                displayIndex: 1,
                printIndex: 0,
                name: "Σκέτο",
                pictureUri: "",
                servingSpots: "All",
                price: 0,
                increacesPrice: true,
                reducesPrice: true,
                isDefault: false,
              },
            ],
          },
          {
            id: "31e3561d-20d0-49e0-a18d-04c3167bc88a",
            name: "Μαύρη",
            parentName: "Επιλογή Ζάχαρης",
            color: "#FFF",
            pictureUri: "",
            displayIndex: 0,
            printIndex: 0,
            selectionBehavior: "Single",
            mandatory: false,
            subGroups: [],
            modifiers: [
              {
                id: "537f6b43-ebb7-46ec-8a6a-4d1cde387070",
                color: "#FFF",
                displayIndex: 0,
                printIndex: 0,
                name: "Σκέτο",
                pictureUri: "",
                servingSpots: "All",
                price: 0,
                increacesPrice: true,
                reducesPrice: true,
                isDefault: false,
                hasQuantity: true,
                maxQuantity: 5,
              },
              {
                id: "7dfba053-561c-488e-99e6-20551cfd42bb",
                color: "#FFF",
                displayIndex: 2,
                printIndex: 0,
                name: "Γλυκό",
                pictureUri: "",
                servingSpots: "All",
                price: 0,
                increacesPrice: true,
                reducesPrice: true,
                isDefault: false,
              },
              {
                id: "ad06f876-2547-4896-876a-aff39246e48e",
                color: "#FFF",
                displayIndex: 1,
                printIndex: 0,
                name: "Μέτριο",
                pictureUri: "",
                servingSpots: "All",
                price: 20,
                increacesPrice: true,
                reducesPrice: true,
                isDefault: false,
              },
            ],
          },
          {
            id: "76ff1963-276f-4ae9-99ad-8007499eda78",
            name: "Ζαχαρίνη",
            parentName: "Επιλογή Ζάχαρης",
            color: "#FFF",
            pictureUri: "",
            displayIndex: 0,
            printIndex: 0,
            selectionBehavior: "Single",
            mandatory: false,
            subGroups: [],
            modifiers: [
              {
                id: "3d5e2b64-5048-46e6-a018-c43e7beddd27",
                color: "#FFF",
                displayIndex: 0,
                printIndex: 0,
                name: "Σκέτο",
                pictureUri: "",
                servingSpots: "All",
                price: 0,
                increacesPrice: true,
                reducesPrice: true,
                isDefault: false,
              },
              {
                id: "516f9651-7bae-4baa-ba6c-c009e691e697",
                color: "#FFF",
                displayIndex: 1,
                printIndex: 0,
                name: "Μέτριο",
                pictureUri: "",
                servingSpots: "All",
                price: 30,
                increacesPrice: true,
                reducesPrice: true,
                isDefault: true,
                hasQuantity: true,
                maxQuantity: 5,
              },
              {
                id: "f1d1a124-2bec-4d91-b87b-b9c1c4b38f84",
                color: "#FFF",
                displayIndex: 2,
                printIndex: 0,
                name: "Γλυκό",
                pictureUri: "",
                servingSpots: "All",
                price: 0,
                increacesPrice: true,
                reducesPrice: true,
                isDefault: false,
              },
            ],
          },
        ],
        modifiers: [],
      },
    ],
    synthesisConsumables: [
      {
        id: "4f791bee-d889-425b-9510-08c4a58b161a",
        color: "#FFF",
        displayIndex: 0,
        printIndex: 0,
        name: "Καλαμακι Πλαστικό",
        pictureUri: "",
        servingSpots: "Delivery,TakeOut",
        price: 0,
        increacesPrice: true,
        reducesPrice: true,
        isDefault: true,
      },
    ],
    instructions: [
      "Not enough salt",
      "Enough salt",
      "Not enough sugar",
      "Please add sugar",
    ],
  },
};

export default debugItem;
