import { StyleSheet } from "aphrodite";
import oda from "../../common/theme/oda";

export default StyleSheet.create({
  pageContainer: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    backgroundColor: oda.colors.surface,
    padding: "16px 48px",
    borderRadius: 4,
  },
  storeName: {
    fontSize: oda.fonts.xxlarge,
    lineHeight: oda.lineHeights.xxlarge,
    fontWeight: 500,
    color: oda.colors.primary,
    fontFamily: oda.fontFamilies.labels,
    textAlign: "center",
    "@media (max-width: 680px)": {
      display: "block",
      textAlign: "center",
    },
  },
  smallFlex: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  smallHeader: {
    fontSize: oda.fonts.large,
    lineHeight: oda.lineHeights.large,
    color: oda.colors.primary,
    display: "block",
    fontFamily: oda.fontFamilies.labels,
  },
  storeDescription: {
    fontSize: oda.fonts.vsmall,
    lineHeight: oda.lineHeights.vsmall,
    color: oda.colors.primary,
    display: "block",
    fontFamily: oda.fontFamilies.labels,
    marginTop: 10,
  },
  fieldValue: {
    fontSize: oda.fonts.small,
    lineHeight: oda.lineHeights.small,
    color: oda.colors.primary,
    display: "block",
    cursor: "pointer",
    wordBreak: "break-word",
    whiteSpace: "wrap",
  },
  twoGrid: {
    display: "grid",
    gridTemplateColumns: "calc(50% - 12px) calc(50% - 12px)",
    gridGap: "24px",
    width: "100%",
    marginTop: 24,
  },
  marginTop24: {
    marginTop: 24,
  },
  threeGrid: {
    display: "grid",
    gridTemplateColumns: "calc(33% - 16px) calc(33% - 16px)  calc(33% - 16px)",
    gridGap: "24px",
    width: "100%",
    "@media (max-width: 680px)": {
      gridTemplateColumns: "calc(50% - 12px) calc(50% - 12px)",
      gridGap: 24,
    },
    "@media (max-width: 500px)": {
      gridTemplateColumns: "100%",
    },
  },
  flex: {
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
    marginTop: 24,
  },
  wrapper: {
    backgroundColor: oda.colors.background + "69",
    borderRadius: 4,
    padding: 16,
    marginTop: 24,
  },
  shopIcon: {
    width: "80px",
    height: "80px",
    display: "block",
    padding: "8px",
    boxShadow: oda.boxShadows.faint,
    borderRadius: "50%",
    margin: "0px auto 0px auto",
    objectFit: "contain",
    backgroundColor: oda.colors.surface,
  },
  disabledColor: {
    color: oda.colors.disabled,
  },
  greenColor: {
    color: oda.colors.success,
  },
  redColor: {
    color: oda.colors.danger,
  },
  header: {
    fontSize: oda.fonts.normal,
    lineHeight: oda.lineHeights.normal,
    color: oda.colors.disabled,
    display: "block",
    cursor: "pointer",
    whiteSpace: "wrap",
  },
  openStore: {
    fontSize: oda.fonts.large,
    lineHeight: oda.lineHeights.large,
    display: "block",
    fontFamily: oda.fontFamilies.labels,
    textAlign: "left",
    color: oda.colors.success,
    fontWeight: 500,
    "@media (max-width: 680px)": {
      display: "block",
      textAlign: "center",
    },
  },
  closedStore: {
    fontSize: oda.fonts.large,
    lineHeight: oda.lineHeights.large,
    display: "block",
    fontFamily: oda.fontFamilies.labels,
    fontWeight: 500,
    textAlign: "left",
    color: oda.colors.danger,
  },
  socialMediaIcon: {
    width: 24,
    height: 24,
    objectFit: "contain",
    cursor: "pointer",
    margin: "auto",
  },
  websiteIcon: {
    width: 30,
    height: 30,
    objectFit: "contain",
    cursor: "pointer",
    margin: "auto",
  },
  fieldValueSmall: {
    fontSize: oda.fonts.small,
    lineHeight: oda.lineHeights.small,
    color: oda.colors.primary,
    display: "block",
    cursor: "pointer",
    wordBreak: "break-all",
    whiteSpace: "wrap",
  },
  headerSmall: {
    fontSize: oda.fonts.small,
    lineHeight: oda.lineHeights.small,
    color: oda.colors.disabled,
    display: "block",
    cursor: "pointer",
    whiteSpace: "wrap",
  },
});
