export default [
  {
    name: "Perioxi A",
    description: "Pergrafh Perioxhs A",
    isMain: true,
    storeId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    displayIndex: 0,
    id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    createdOn: "2022-02-14T08:07:38.386Z",
    enabled: true,
    xScale: 0,
    yScale: 0,
    picture: {
      description: "perigrafh eikonas perioxhs A",
      url: "string",
    },
    subSectors: [
      {
        name: "Sector 1 Perioxhs A",
        description: "Perigrafh Sector1 Perioxhs A",
        isMain: true,
        storeId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        displayIndex: 0,
        id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        createdOn: "2022-02-14T08:07:38.387Z",
        enabled: true,
        xScale: 0,
        yScale: 0,
        picture: {
          description: "string",
          url: "string",
        },
        subSectors: [],
        concurrencyToken: 0,
        servicePoints: [
          {
            id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            createdOn: "2022-02-14T08:07:38.387Z",
            enabled: true,
            description: "string",
            name: "T 1",
            minConsumption: 100.57,
            displayIndex: 0,
            capacity: 2,
            status: 0,
            xLocation: 0,
            yLocation: 0,
            shape: 0,
            design: "string",
            concurrencyToken: 0,
            pictures: [
              {
                description: "string",
                url: "https://oda-bucket.s3.us-west-000.backblazeb2.com/69304377_522664035155572_2003756952600969216_n.jpg",
              },
              {
                description: "string",
                url: "https://oda-bucket.s3.us-west-000.backblazeb2.com/68601065_522664021822240_1714029982210064384_n.jpg",
              },
            ],
          },
          {
            id: "3fa85f64-571cx7-4562-b3fc-2c963f66afa6",
            createdOn: "2022-02-14T08:07:38.387Z",
            enabled: true,
            description: "string",
            name: "T 2",
            minConsumption: 1000.86,
            displayIndex: 0,
            capacity: 4,
            status: 0,
            xLocation: 0,
            yLocation: 0,
            shape: 0,
            design: "string",
            concurrencyToken: 0,
            pictures: [
              {
                description: "string",
                url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Ffood&psig=AOvVaw3X0B6D7P_pbg2L1MEp63BG&ust=1644933880117000&source=images&cd=vfe&ved=0CAgQjRxqFwoTCIDamq6u__UCFQAAAAAdAAAAABAE",
              },
              {
                description: "string",
                url: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fclicklovegrow.com%2F15-delicious-food-photos-a-beginners-guide-to-food-photography%2F&psig=AOvVaw3X0B6D7P_pbg2L1MEp63BG&ust=1644933880117000&source=images&cd=vfe&ved=0CAgQjRxqFwoTCIDamq6u__UCFQAAAAAdAAAAABAK",
              },
            ],
          },
          {
            id: "3fa85f64-57cx17-4562-b3fc-2c963f66afa6",
            createdOn: "2022-02-14T08:07:38.387Z",
            enabled: true,
            description: "string",
            name: "T 3",
            minConsumption: 856,
            displayIndex: 0,
            capacity: 5,
            status: 0,
            xLocation: 0,
            yLocation: 0,
            shape: 0,
            design: "string",
            concurrencyToken: 0,
            pictures: [
              {
                description: "",
                url: "",
              },
            ],
          },
        ],
      },
      {
        name: "Sector 2 Perioxhs A",
        description: "Perigrafh Sector1 Perioxhs A",
        isMain: true,
        storeId: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        displayIndex: 0,
        id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        createdOn: "2022-02-14T08:07:38.387Z",
        enabled: true,
        xScale: 0,
        yScale: 0,
        picture: {
          description: "string",
          url: "string",
        },
        subSectors: [],
        concurrencyToken: 0,
        servicePoints: [
          {
            id: "3fa85f64-5717-45sdf62-b3fc-2c963f66afa6",
            createdOn: "2022-02-14T08:07:38.387Z",
            enabled: true,
            description: "string",
            name: "T 1",
            minConsumption: 0,
            displayIndex: 0,
            capacity: 0,
            status: 0,
            xLocation: 0,
            yLocation: 0,
            shape: 0,
            design: "string",
            concurrencyToken: 0,
            pictures: [
              {
                description: "string",
                url: "string",
              },
            ],
          },
          {
            id: "3fa85f64-571sfdcx7-4562-b3fc-2c963f66afa6",
            createdOn: "2022-02-14T08:07:38.387Z",
            enabled: true,
            description: "string",
            name: "T 2",
            minConsumption: 0,
            displayIndex: 0,
            capacity: 0,
            status: 0,
            xLocation: 0,
            yLocation: 0,
            shape: 0,
            design: "string",
            concurrencyToken: 0,
            pictures: [
              {
                description: "string",
                url: "string",
              },
            ],
          },
          {
            id: "3fa85f64-57csdfx17-4562-b3fc-2c963f66afa6",
            createdOn: "2022-02-14T08:07:38.387Z",
            enabled: true,
            description: "string",
            name: "T 3",
            minConsumption: 0,
            displayIndex: 0,
            capacity: 0,
            status: 0,
            xLocation: 0,
            yLocation: 0,
            shape: 0,
            design: "string",
            concurrencyToken: 0,
            pictures: [
              {
                description: "string",
                url: "string",
              },
            ],
          },
        ],
      },
      {
        name: "Sector 3 Perioxhs A",
        description: "Perigrafh Sector1 Perioxhs A",
        isMain: true,
        storeId: "3fa85f64-5717-45sdf62-b3fc-2c963f66afa6",
        displayIndex: 0,
        id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        createdOn: "2022-02-14T08:07:38.387Z",
        enabled: true,
        xScale: 0,
        yScale: 0,
        picture: {
          description: "string",
          url: "string",
        },
        subSectors: [
          {
            name: "Sector 1 sector3 Perioxhs A",
            description: "Perigrafh Sector1 Perioxhs A",
            isMain: true,
            storeId: "3fa85f64-5717-456sdf2-b3fc-2c963f66afa6",
            displayIndex: 0,
            id: "3fa85f64-5717-4562-b3fc-2c963f66afa6",
            createdOn: "2022-02-14T08:07:38.387Z",
            enabled: true,
            xScale: 0,
            yScale: 0,
            picture: {
              description: "string",
              url: "string",
            },
            subSectors: [],
            concurrencyToken: 0,
            servicePoints: [
              {
                id: "3fa85f64-5717-45sdfsdf62-b3fc-2c963f66afa6",
                createdOn: "2022-02-14T08:07:38.387Z",
                enabled: true,
                description: "string",
                name: "T 1",
                minConsumption: 0,
                displayIndex: 0,
                capacity: 0,
                status: 0,
                xLocation: 0,
                yLocation: 0,
                shape: 0,
                design: "string",
                concurrencyToken: 0,
                pictures: [
                  {
                    description: "string",
                    url: "string",
                  },
                ],
              },
              {
                id: "3fa85f64-571cx7-45sdfsdf62-b3fc-2c963f66afa6",
                createdOn: "2022-02-14T08:07:38.387Z",
                enabled: true,
                description: "string",
                name: "T 2",
                minConsumption: 0,
                displayIndex: 0,
                capacity: 0,
                status: 0,
                xLocation: 0,
                yLocation: 0,
                shape: 0,
                design: "string",
                concurrencyToken: 0,
                pictures: [
                  {
                    description: "string",
                    url: "string",
                  },
                ],
              },
              {
                id: "3fa85f64-57cx17-45sdfsdf62-b3fc-2c963f66afa6",
                createdOn: "2022-02-14T08:07:38.387Z",
                enabled: true,
                description: "string",
                name: "T 3",
                minConsumption: 0,
                displayIndex: 0,
                capacity: 0,
                status: 0,
                xLocation: 0,
                yLocation: 0,
                shape: 0,
                design: "string",
                concurrencyToken: 0,
                pictures: [
                  {
                    description: "string",
                    url: "string",
                  },
                ],
              },
            ],
          },
        ],
        concurrencyToken: 0,
        servicePoints: [],
      },
    ],
    concurrencyToken: 0,
    servicePoints: [],
  },
];
